#!/usr/bin/env python3
"""Read-only source/provenance checks for bundled Scripture editions.

This tool never rewrites Scripture.  The initial implementation compares the
English in-app OT/NT corpus with the supplied Berean Standard Bible USFM tree.
It deliberately reports text and red-letter markup separately so display tags
cannot hide a wording difference.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
from pathlib import Path
import re
import sys
import unicodedata


BOOKS: tuple[tuple[str, str, str], ...] = (
    ("GEN", "old_testament", "genesis"),
    ("EXO", "old_testament", "exodus"),
    ("LEV", "old_testament", "leviticus"),
    ("NUM", "old_testament", "numbers"),
    ("DEU", "old_testament", "deuteronomy"),
    ("JOS", "old_testament", "joshua"),
    ("JDG", "old_testament", "judges"),
    ("RUT", "old_testament", "ruth"),
    ("1SA", "old_testament", "1_samuel"),
    ("2SA", "old_testament", "2_samuel"),
    ("1KI", "old_testament", "1_kings"),
    ("2KI", "old_testament", "2_kings"),
    ("1CH", "old_testament", "1_chronicles"),
    ("2CH", "old_testament", "2_chronicles"),
    ("EZR", "old_testament", "ezra"),
    ("NEH", "old_testament", "nehemiah"),
    ("EST", "old_testament", "esther"),
    ("JOB", "old_testament", "job"),
    ("PSA", "old_testament", "psalms"),
    ("PRO", "old_testament", "proverbs"),
    ("ECC", "old_testament", "ecclesiastes"),
    ("SNG", "old_testament", "song_of_songs"),
    ("ISA", "old_testament", "isaiah"),
    ("JER", "old_testament", "jeremiah"),
    ("LAM", "old_testament", "lamentations"),
    ("EZK", "old_testament", "ezekiel"),
    ("DAN", "old_testament", "daniel"),
    ("HOS", "old_testament", "hosea"),
    ("JOL", "old_testament", "joel"),
    ("AMO", "old_testament", "amos"),
    ("OBA", "old_testament", "obadiah"),
    ("JON", "old_testament", "jonah"),
    ("MIC", "old_testament", "micah"),
    ("NAM", "old_testament", "nahum"),
    ("HAB", "old_testament", "habakkuk"),
    ("ZEP", "old_testament", "zephaniah"),
    ("HAG", "old_testament", "haggai"),
    ("ZEC", "old_testament", "zechariah"),
    ("MAL", "old_testament", "malachi"),
    ("MAT", "new_testament", "matthew"),
    ("MRK", "new_testament", "mark"),
    ("LUK", "new_testament", "luke"),
    ("JHN", "new_testament", "john"),
    ("ACT", "new_testament", "acts"),
    ("ROM", "new_testament", "romans"),
    ("1CO", "new_testament", "1_corinthians"),
    ("2CO", "new_testament", "2_corinthians"),
    ("GAL", "new_testament", "galatians"),
    ("EPH", "new_testament", "ephesians"),
    ("PHP", "new_testament", "philippians"),
    ("COL", "new_testament", "colossians"),
    ("1TH", "new_testament", "1_thessalonians"),
    ("2TH", "new_testament", "2_thessalonians"),
    ("1TI", "new_testament", "1_timothy"),
    ("2TI", "new_testament", "2_timothy"),
    ("TIT", "new_testament", "titus"),
    ("PHM", "new_testament", "philemon"),
    ("HEB", "new_testament", "hebrews"),
    ("JAS", "new_testament", "james"),
    ("1PE", "new_testament", "1_peter"),
    ("2PE", "new_testament", "2_peter"),
    ("1JN", "new_testament", "1_john"),
    ("2JN", "new_testament", "2_john"),
    ("3JN", "new_testament", "3_john"),
    ("JUD", "new_testament", "jude"),
    ("REV", "new_testament", "revelation"),
)

TRAILING_REFERENCE = re.compile(r"\s+\((\d+):(\d+)(?:-(\d+))?\)\.?\s*$")
APP_TAG = re.compile(r"\[/?(?:J|ADD|DN)\]")
MARKER = re.compile(r"\\([+A-Za-z0-9-]+)(\*)?")

# The supplied autogenerated USFM contains two repeatable export defects. They
# are not printed by Bible.com: a literal [’’] token at 59 verse endings and a
# stray ``vvv`` token in three inline notes. Keep this normalization narrow so
# a real wording difference still fails the audit.
BROKEN_FOOTNOTE_TOKEN = "[\u2019\u2019]"

# These two live Bible.com readings differ from the supplied export. Pin the
# reviewed display text so a later change cannot pass merely because its
# reference appears in an exception list.
LIVE_BSB_TEXT = {
    ("habakkuk", 3, 19): (
        "GOD the Lord is my strength; He makes my feet like those of a deer; "
        "He makes me walk upon the heights! For the choirmaster. With stringed instruments."
    ),
    ("2_timothy", 1, 15): (
        "You know that everyone in the Province of Asia has deserted me, "
        "including Phygelus and Hermogenes."
    ),
}
STRUCTURAL_MARKERS = {
    "id", "usfm", "h", "toc1", "toc2", "toc3", "mt1", "mt2",
    "ms", "mr", "s1", "s2", "r",
}
FLOW_MARKERS = {"p", "pc", "pmo", "q1", "q2", "qr", "li1", "li2", "b"}


class AuditError(RuntimeError):
    pass


@dataclass(frozen=True)
class Verse:
    plain: str
    marked: str


def normalized(value: str) -> str:
    return " ".join(unicodedata.normalize("NFC", value).split())


def plain_app_text(value: str) -> str:
    return normalized(APP_TAG.sub("", value))


def normalize_known_source_artifacts(value: str) -> str:
    cleaned = value.replace(BROKEN_FOOTNOTE_TOKEN, "").replace("vvv", "")
    return normalized(re.sub(r"\(\s+", "(", cleaned))


def j_mask(value: str) -> tuple[bool, ...]:
    """Return red-letter state for each non-whitespace display character."""
    normalized_value = unicodedata.normalize("NFC", value)
    state = False
    result: list[bool] = []
    position = 0
    for match in APP_TAG.finditer(normalized_value):
        for character in normalized_value[position : match.start()]:
            if not character.isspace():
                result.append(state)
        tag = match.group(0)
        if tag == "[J]":
            state = True
        elif tag == "[/J]":
            state = False
        position = match.end()
    for character in normalized_value[position:]:
        if not character.isspace():
            result.append(state)
    return tuple(result)


def parse_app_book(path: Path) -> dict[tuple[int, int], Verse]:
    payload = json.loads(path.read_text(encoding="utf-8-sig"))
    result: dict[tuple[int, int], Verse] = {}
    for story in payload.get("stories", []):
        for raw in story.get("summaryBullets", []):
            match = TRAILING_REFERENCE.search(raw)
            if match is None:
                raise AuditError(f"unparseable Scripture bullet in {path}: {raw[:120]!r}")
            chapter, start = int(match.group(1)), int(match.group(2))
            # A few modern BSB lines cover a traditional extra verse number
            # (3 John 14-15 and Revelation 12:17-18). Bible.com presents each
            # as one text unit and notes the alternate numbering. Key the
            # combined unit by its first verse so it compares with that source
            # line without pretending the second number has separate wording.
            end = int(match.group(3) or start)
            marked = normalized(raw[: match.start()])
            key = (chapter, start)
            if key in result:
                raise AuditError(f"duplicate app verse in {path}: {chapter}:{start}")
            if end < start:
                raise AuditError(f"reversed app verse range in {path}: {chapter}:{start}-{end}")
            result[key] = Verse(plain_app_text(marked), marked)
    return result


def parse_bsb_usfm(path: Path) -> dict[tuple[int, int], Verse]:
    """Parse the marker subset used by the supplied autogenerated BSB USFM."""
    source = path.read_text(encoding="utf-8-sig")
    is_psalms = path.stem.upper() == "PSA"
    chapter: int | None = None
    verse: int | None = None
    capture = False
    footnote_depth = 0
    word_of_jesus = False
    buffers: dict[tuple[int, int], list[str]] = {}
    marked_buffers: dict[tuple[int, int], list[str]] = {}
    i = 0

    def append(value: str) -> None:
        if not capture or chapter is None or verse is None or footnote_depth:
            return
        key = (chapter, verse)
        buffers.setdefault(key, []).append(value)
        marked_buffers.setdefault(key, []).append(value)

    while i < len(source):
        if source[i] != "\\":
            end = source.find("\\", i)
            if end < 0:
                end = len(source)
            append(source[i:end])
            i = end
            continue

        match = MARKER.match(source, i)
        if match is None:
            raise AuditError(f"invalid USFM marker at {path}:{i}")
        marker = match.group(1).removeprefix("+")
        closing = bool(match.group(2))
        i = match.end()

        if footnote_depth:
            if marker == "f" and closing:
                footnote_depth -= 1
            elif marker == "f" and not closing:
                footnote_depth += 1
            continue

        if marker == "f":
            if closing:
                raise AuditError(f"unexpected footnote close in {path}")
            footnote_depth = 1
            continue

        if marker == "c" and not closing:
            number = re.match(r"\s+(\d+)", source[i:])
            if number is None:
                raise AuditError(f"chapter marker without number in {path}")
            chapter = int(number.group(1))
            verse = None
            capture = False
            word_of_jesus = False
            i += number.end()
            continue

        if marker == "v" and not closing:
            number = re.match(r"\s+(\d+)", source[i:])
            if number is None or chapter is None:
                raise AuditError(f"verse marker without chapter/number in {path}")
            verse = int(number.group(1))
            key = (chapter, verse)
            if key in buffers:
                raise AuditError(f"duplicate BSB verse in {path}: {chapter}:{verse}")
            buffers[key] = []
            marked_buffers[key] = ["[J]"] if word_of_jesus else []
            capture = True
            i += number.end()
            continue

        if marker == "wj":
            if closing:
                if word_of_jesus and capture and chapter is not None and verse is not None:
                    marked_buffers[(chapter, verse)].append("[/J]")
                word_of_jesus = False
            else:
                word_of_jesus = True
                if capture and chapter is not None and verse is not None:
                    marked_buffers[(chapter, verse)].append("[J]")
            continue

        if marker == "ref" and not closing:
            end = source.find("\\ref*", i)
            if end < 0:
                raise AuditError(f"unclosed ref marker in {path}")
            visible = source[i:end].split("|", 1)[0].lstrip()
            append(visible)
            i = end + len("\\ref*")
            continue

        if marker == "d" and not closing:
            line_end = source.find("\n", i)
            line_end = len(source) if line_end < 0 else line_end
            embedded_verse = source.find("\\v ", i, line_end)
            if embedded_verse < 0:
                capture = False
                i = min(len(source), line_end + 1)
                continue
            if not is_psalms:
                capture = False
                i = embedded_verse
                continue
            number = re.match(r"\\v\s+(\d+)", source[embedded_verse:line_end])
            if number is None or chapter is None:
                raise AuditError(f"Psalm superscription without chapter/verse in {path}")
            verse = int(number.group(1))
            key = (chapter, verse)
            if key in buffers:
                raise AuditError(f"duplicate BSB verse in {path}: {chapter}:{verse}")
            # The BSB stores the numbered Psalm superscription after \d \v N.
            # The app stores the same text as a heading, not in the verse body.
            buffers[key] = []
            marked_buffers[key] = []
            capture = False
            i = min(len(source), line_end + 1)
            continue

        if marker == "qa" and not closing:
            # Speaker/acrostic labels are presentation data.  Some occur inside
            # a verse, so skip only this line and retain the active verse.
            line_end = source.find("\n", i)
            i = len(source) if line_end < 0 else line_end + 1
            continue

        if marker in STRUCTURAL_MARKERS:
            capture = False
            line_end = source.find("\n", i)
            line_end = len(source) if line_end < 0 else line_end
            # BSB encodes numbered Psalm superscriptions and Zechariah 12:1
            # as ``\d \v N ...``.  The text before \v is presentation data,
            # but the verse marker and everything after it are Scripture.
            embedded_verse = source.find("\\v ", i, line_end)
            i = embedded_verse if embedded_verse >= 0 else min(len(source), line_end + 1)
            continue

        if marker in FLOW_MARKERS:
            capture = verse is not None
            while i < len(source) and source[i] in " \t":
                i += 1
            continue

        raise AuditError(f"unsupported BSB marker {marker!r} in {path}")

    if footnote_depth:
        raise AuditError(f"unclosed footnote in {path}")
    result: dict[tuple[int, int], Verse] = {}
    for key, chunks in buffers.items():
        plain = normalized("".join(chunks))
        marked = normalized("".join(marked_buffers[key]))
        if marked.endswith("[J]") and word_of_jesus:
            marked += "[/J]"
        if not plain:
            raise AuditError(f"empty BSB verse in {path}: {key[0]}:{key[1]}")
        result[key] = Verse(plain, marked)
    return result


def compare_bsb(repo: Path, source: Path) -> dict:
    missing_source: list[str] = []
    missing_app: list[str] = []
    text_differences: list[dict[str, str]] = []
    unresolved_text_differences: list[str] = []
    markup_differences: list[str] = []
    total_app = total_source = exact_text = exact_marked = 0
    per_book: list[dict] = []

    for code, collection, book in BOOKS:
        app_path = repo / "shared" / "assets" / "books" / collection / "en" / f"{book}.json"
        source_path = source / f"{code}.usfm"
        if not app_path.is_file() or not source_path.is_file():
            raise AuditError(f"missing comparison input: {app_path} or {source_path}")
        app = parse_app_book(app_path)
        bsb = parse_bsb_usfm(source_path)
        total_app += len(app)
        total_source += len(bsb)
        book_text = book_marked = 0
        for key in sorted(set(app) | set(bsb)):
            ref = f"{book} {key[0]}:{key[1]}"
            if key not in bsb:
                missing_source.append(ref)
                continue
            if key not in app:
                missing_app.append(ref)
                continue
            if app[key].plain == bsb[key].plain:
                exact_text += 1
                book_text += 1
            else:
                normalized_source = normalize_known_source_artifacts(bsb[key].plain)
                if app[key].plain == normalized_source:
                    classification = "known-source-export-artifact"
                elif LIVE_BSB_TEXT.get((book, key[0], key[1])) == app[key].plain:
                    classification = "reviewed-live-biblecom-reading"
                else:
                    classification = "unresolved"
                    unresolved_text_differences.append(ref)
                text_differences.append(
                    {
                        "reference": ref,
                        "classification": classification,
                        "app": app[key].plain,
                        "source": bsb[key].plain,
                    }
                )
            if app[key].plain == bsb[key].plain and j_mask(app[key].marked) == j_mask(bsb[key].marked):
                exact_marked += 1
                book_marked += 1
            elif app[key].plain == bsb[key].plain:
                markup_differences.append(ref)
        per_book.append(
            {
                "book": book,
                "appVerses": len(app),
                "sourceVerses": len(bsb),
                "exactText": book_text,
                "exactTextAndJMarkup": book_marked,
            }
        )

    return {
        "source": "supplied Berean Standard Bible USFM",
        "sourceDirectory": str(source),
        "appVerses": total_app,
        "sourceVerses": total_source,
        "exactText": exact_text,
        "exactTextAndJMarkup": exact_marked,
        "missingFromSource": missing_source,
        "missingFromApp": missing_app,
        "textDifferenceCount": len(text_differences),
        "adjudicatedTextCount": exact_text + len(text_differences) - len(unresolved_text_differences),
        "unresolvedTextDifferenceCount": len(unresolved_text_differences),
        "unresolvedTextDifferences": unresolved_text_differences,
        "textDifferences": text_differences,
        "jMarkupDifferenceCountOnExactText": len(markup_differences),
        "jMarkupDifferencesOnExactText": markup_differences,
        "books": per_book,
    }


def main() -> int:
    repo = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bsb-source", type=Path, required=True)
    parser.add_argument("--report", type=Path)
    parser.add_argument("--compact", action="store_true")
    args = parser.parse_args()
    try:
        result = compare_bsb(repo, args.bsb_source.resolve())
    except (AuditError, OSError, UnicodeError, ValueError, KeyError) as exc:
        print(f"Scripture source audit failed: {exc}", file=sys.stderr)
        return 2
    rendered_result = result
    if args.compact:
        rendered_result = {
            key: value
            for key, value in result.items()
            if key not in {"books"}
        }
        rendered_result["textDifferenceReferences"] = [
            item["reference"] for item in result["textDifferences"]
        ]
        rendered_result["books"] = result["books"]
    rendered = json.dumps(rendered_result, ensure_ascii=False, indent=2) + "\n"
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(rendered, encoding="utf-8", newline="\n")
    print(rendered, end="")
    return 1 if result["unresolvedTextDifferenceCount"] or result["missingFromApp"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
